### ISSUE TITLE
Do fizzbuzz

### ISSUE THREAD

**Issue by LDHIUM** [LDHIUM/Gh_Flow_Practice_#2]
## Tasks

- [x] Print fizz, if is multiple of 3
- [x] Print buzz, if is multiple of 5
- [ ] print fizzbuzz, if i is multiple of 15
- [x] Otherwise, print i itself.

## References

-[Fizzbuzz wikipedia](https://en.wikipedia.org/wiki/Fizz_buzz)
